### ISSUE TITLE
PAL output not supported

### ISSUE THREAD

**Issue by sfahadshahzad** [freehand-dev/FFMpegDecoder#2]
Hi,

How I can get PAL output?

  "Output": {
      "Device": "DeckLink Quad (1)",
      "Format?": "UYVY422_1920i50 or UYVY422_720p25 or UYVY422_720p50 or UYVY422_1920p25 or UYVY422_1920p50",
      "Format": "UYVY422_1920i50"

Regards,

Fahad

**Comment by freehand-dev** [comment]
Hi,
SD? No, we do not use SD in production. But I will look and add such an opportunity. (without testing).

Regards,

**Comment by freehand-dev** [comment]
Hi,

I added two formats
UYVY422_576i50 
and 
PASS - pass source video format (ignored  -s, -r and -field_order options)
